config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'orders/show', to: 'orders#show'
  # get 'orders/index', to: 'orders#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'items#index'
  resources :items, only: %i[show]
  resources :order_items, only: %i[create update destroy]
  resource :cart, only: %i[show]
  resources :orders, only: %i[index show]

  devise_for :users, path: 'users', controllers: { registrations: 'users/registrations' }

  resources :charges

  namespace 'administration' do
    get '/', to: 'items#index'
    resources :items
    resources :orders, only: %i[index show create]
  end
end

app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id          :bigint(8)        not null, primary key
#  name        :string
#  description :text
#  price       :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Item < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  has_one_attached :image

  validates :name, :description, :price, presence: true
  validates :name, length: { in: 2..40 }
  validates :description, length: { in: 2..400 }
end

app/controllers/administration/items_controller.rb
# frozen_string_literal: true

module Administration
  class ItemsController < AdministrationController
    before_action :set_item, only: %i[edit show update destroy]
    def index
      @items = Item.paginate(page: params[:page])
    end

    def show; end

    def new
      @item = Item.new
    end

    def create
      @item = Item.new(item_params)
      @item.save
      redirect_to administration_items_path
    end

    def edit; end

    def update
      @item.update(item_params)
      redirect_to administration_items_path
    end

    def destroy
      @item.destroy
      redirect_to administration_items_path
    end

    private

      def set_item
        @item = Item.find(params[:id])
      end

      def item_params
        params.require(:item).permit(:name, :description, :price, :image)
      end
  end
end

app/controllers/administration/orders_controller.rb
# frozen_string_literal: true

module Administration
  class OrdersController < AdministrationController
    before_action :set_orders, only: %i[index]
    before_action :set_order, only: %i[show create]
    before_action :set_order_items, only: %i[show]

    def index; end

    def show; end

    def create
      @order.update(status: "treated")
      redirect_back fallback_location: administration_orders_path, notice: "Vous avez bien validé votre commande"
    end

    private

      def set_orders
        @orders = Order.all_except('biding').order(:status).paginate(page: params[:page])
      end

      def set_order
        @order = Order.find(params[:id])
      end

      def set_order_items
        @order_items = @order.order_items
      end
  end
end

app/controllers/administration/static_pages_controller.rb
# frozen_string_literal: true

module Administration
  class StaticPagesController < AdministrationController
    def hello_admin; end

    def template; end
  end
end

app/controllers/administration_controller.rb
# frozen_string_literal: true

class AdministrationController < ApplicationController
  before_action :authenticate_admin!
  layout 'administration'

  private

    def authenticate_admin!
      authenticate_user!
      redirect_to root_url unless current_user.admin
    end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: [:show]

  def index
    @items = Item.paginate(page: params[:page], per_page: 18)
  end

  def show; end

  private

    def set_item
      @item = Item.find(params[:id])
    end
end

app/views/administration/items/_item.html.erb
<tr>
  <td><%= item.name %></td>
  <td>
    <% if item.description.length > 97  %>
      <%= item.description.slice(0..100) %>...
    <% else %>
      <%= item.description %>
    <% end %>
  </td>
  <td><%= number_to_currency item.price, unit: "€", separator: ",", format: "%n%u"  %></td>
  <td><%= link_to "Infos", administration_item_path(item) %></td>
  <td><%= link_to "Changer",  edit_administration_item_path(item.id) %></td>
  <td><%= link_to "Supprimer", administration_item_path(item),
      method: :delete,
      data: { confirm: "Are you sure?" } %></td>
</tr>

app/views/administration/items/edit.html.erb
<%= link_to "Retour aux produits", administration_items_path %> |
<%= link_to "Infos du produit", administration_item_path(@item) %> |
<%= link_to "Supprimer ce produit", administration_item_path(@item),
      method: :delete,
      data: { confirm: "Are you sure?" } %> |
<%= link_to "Voir le produit",  item_path(@item) %>

<%= form_for @item, url: administration_item_url(@item), html: {class: ""} do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.file_field :image, :class => "form-control" %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/administration/items/index.html.erb
<main class="content">
  <div class="container-fluid p-0">
    <h1 class="h3 mb-3"><strong>Liste des items</strong></h1>
    <%= link_to "Créer un nouvel item", new_administration_item_path %>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Nom</th>
                  <th>Description</th>
                  <th>Prix</th>
                </tr>
              </thead>
              <tbody>
                <%= render @items %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <%= will_paginate @items, renderer: WillPaginate::ActionView::BootstrapLinkRenderer,
                              list_classes: %w(pagination justify-content-center) %>
  </div>
</main>

app/views/administration/items/new.html.erb
<%= form_for (@item), :url => {:action => "create"}, html: {class: ""} do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.file_field :image, :class => "form-control" %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/administration/items/show.html.erb
<%= link_to "Retour aux produits", administration_items_path %> |
<%= link_to "Changer ce produit", edit_administration_item_path(@item) %> |
<%= link_to "Supprimer ce produit", administration_item_path(@item),
      method: :delete,
      data: { confirm: "Are you sure?" } %> |
<%= link_to "Voir le produit",  item_path(@item) %>

<div class="card" style="background-image: white">
  <div class="card-category">
    <h1 class="text-center"><%= @item.name %></h1>
  </div>
  <div class="card-description">
    <h2 class="text-center"><%= @item.description %></h2>
    <p class= "text-right"><%= number_to_currency @item.price, unit: "€", separator: ",", format: "%n%u"  %></p>
  </div>
</div>