config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'orders/show', to: 'orders#show'
  # get 'orders/index', to: 'orders#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'items#index'
  resources :items, only: %i[show]
  resources :order_items, only: %i[create update destroy]
  resource :cart, only: %i[show]
  resources :orders, only: %i[index show]

  devise_for :users, path: 'users', controllers: { registrations: 'users/registrations' }

  resources :charges

  namespace 'administration' do
    get '/', to: 'items#index'
    resources :items
    resources :orders, only: %i[index show create]
  end
end

app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id          :bigint(8)        not null, primary key
#  name        :string
#  description :text
#  price       :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Item < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  has_one_attached :image

  validates :name, :description, :price, presence: true
  validates :name, length: { in: 2..40 }
  validates :description, length: { in: 2..400 }
end

app/controllers/administration/items_controller.rb
# frozen_string_literal: true

module Administration
  class ItemsController < AdministrationController
    before_action :set_item, only: %i[edit show update destroy]
    def index
      @items = Item.paginate(page: params[:page])
    end

    def show; end

    def new
      @item = Item.new
    end

    def create
      @item = Item.new(item_params)
      @item.save
      redirect_to administration_items_path
    end

    def edit; end

    def update
      @item.update(item_params)
      redirect_to administration_items_path
    end

    def destroy
      @item.destroy
      redirect_to administration_items_path
    end

    private

      def set_item
        @item = Item.find(params[:id])
      end

      def item_params
        params.require(:item).permit(:name, :description, :price, :image)
      end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: [:show]

  def index
    @items = Item.paginate(page: params[:page], per_page: 18)
  end

  def show; end

  private

    def set_item
      @item = Item.find(params[:id])
    end
end

app/views/items/_item.html.erb
<div class="col-xs-12 col-md-6 col-lg-4 mt-4 mb-4">
  <div class="card border border-primary" style="width: 17rem;">
    <div class="card-block">
      <div class="card-img-top text-center">
        <% if item.image.attached? %>
        <%= link_to image_tag(item.image.variant(resize: "268x268")), item_path(item) %>
        <% else %>
        <%= link_to image_tag("no-image.png", size: "268"), item_path(item) %>
        <% end %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= link_to item.name, item_path(item) %></h5>
      
        <%= link_to "Voir le produit", item_path(item), class: "btn btn-primary" %><p class= "text-right">
        <b><%= number_to_currency item.price, unit: "€", separator: ",", format: "%n%u" %></b>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container-fluid">
  <div class="card-deck">
    <%= render @items %>
  </div>
</div>
​
<%= will_paginate @items, renderer: WillPaginate::ActionView::BootstrapLinkRenderer,
             list_classes: %w(pagination justify-content-center) %>

app/views/items/show.html.erb
<div class="container container-show">
  <div class="row">
    <div class="col-xs-12 col-lg-6">
      <div class="card-image">
       <% if @item.image.attached? %>
       <%= image_tag @item.image.variant(resize: "400x400") %>
       <% else %>
       <%= image_tag("no-image.png", size: "400") %>
       <% end %>
     </div>
   </div>
   <div class="col-xs-12 col-lg-6">
    <h1 class="text-center title-show"><%= @item.name %></h1>

    <div class="card card-white" style="background-image: white">
      <div class="review"><i class="fas fa-star" style ="color:#0cc2aa"></i><i class="fas fa-star" style ="color:#0cc2aa"></i><i class="fas fa-star" style ="color:#0cc2aa"></i><i class="fas fa-star" style ="color:#0cc2aa"></i><i class="fas fa-star" style ="color:#0cc2aa"></i> </div>
      <div class="card-price">
        <p><%= number_to_currency @item.price, unit: "€", separator: ",", format: "%n%u"  %></p>

      </div>

      <% if current_user %>
        <%= link_to 'AJOUTER AU PANIER', order_items_path(item_id: @item.id), method: :create, class: 'btn btn-primary' %>
      <% end %>
      <div class="card-description">
        <p class= "little-title">Détails</p>
        <p class="text-justify"><%= @item.description %></p>

      </div>
    </div>
  </div>
</div>
</div>